-- Seed telescopes from review posts
insert into public.telescopes (slug, brand, model, telescope_type, editorial_rating, is_published) values
  ('celestron-astromaster-114eq-review', 'Celestron', 'Celestron AstroMaster 114EQ Review', 'Bird-Jones Reflector', 2.5, true),
  ('celestron-cpc-1100-gps-review', 'Celestron', 'Celestron CPC 1100 GPS Review', 'Schmidt-Cassegrain', 9.0, true),
  ('celestron-cpc-800-gps-review', 'Celestron', 'Celestron CPC 800 GPS Review', 'Schmidt-Cassegrain', 9.0, true),
  ('celestron-cpc-925-gps-review', 'Celestron', 'Celestron CPC 925 GPS Review', 'Schmidt-Cassegrain', 9.0, true),
  ('celestron-evolution-9-25-review', 'Celestron', 'Celestron Evolution 9.25 Review', 'Schmidt-Cassegrain', 9.0, true),
  ('celestron-firstscope-review', 'Celestron', 'Celestron FirstScope Overview', 'Tabletop Dobsonian', 7.0, true),
  ('celestron-inspire-100az-overview', 'Celestron', 'Celestron Inspire 100AZ Overview', 'Refractor', 7.5, true),
  ('celestron-nexstar-127-slt-review', 'Celestron', 'Celestron NexStar 127 SLT Review', 'Maksutov-Cassegrain', 7.0, true),
  ('celestron-nexstar-4se-overview', 'Celestron', 'Celestron NexStar 4SE Overview', 'Maksutov-Cassegrain', 7.5, true),
  ('celestron-nexstar-5se-overview', 'Celestron', 'Celestron NexStar 5SE Overview', 'Schmidt-Cassegrain', 7.8, true),
  ('celestron-nexstar-6se-overview', 'Celestron', 'Celestron NexStar 6SE Overview', 'Schmidt-Cassegrain', 8.9, true),
  ('celestron-nexstar-8se-overview', 'Celestron', 'Celestron NexStar 8SE Overview', 'Schmidt-Cassegrain', 7.4, true),
  ('celestron-nexstar-evolution-6-review', 'Celestron', 'Celestron NexStar Evolution 6 Overview', 'Schmidt-Cassegrain', 8.8, true),
  ('celestron-nexstar-evolution-8-edgehd-review', 'Celestron', 'Celestron NexStar Evolution 8 EdgeHD with StarSense Overview', 'Schmidt-Cassegrain', 9.5, true),
  ('celestron-powerseeker-114eq-overview', 'Celestron', 'Celestron PowerSeeker 114EQ Overview', 'Reflector', 6.5, true),
  ('celestron-powerseeker-127eq-overview', 'Celestron', 'Celestron PowerSeeker 127EQ Overview', 'Bird-Jones Reflector', 4.0, true),
  ('celestron-starsense-10-review', 'Celestron', 'Celestron StarSense 10 Review', 'Dobsonian', 8.5, true),
  ('celestron-starsense-8-review', 'Celestron', 'Celestron StarSense 8 Review', 'Dobsonian', 8.5, true),
  ('celestron-starsense-explorer-102-review', 'Celestron', 'Celestron Starsense Explorer 102 Review', 'Refractor', 7.0, true),
  ('celestron-starsense-explorer-dx-130az-review', 'Celestron', 'Celestron StarSense Explorer DX 130AZ Review', 'Reflector', 6.0, true),
  ('celestron-starsense-explorer-lt-80az-review', 'Celestron', 'Celestron StarSense Explorer LT 80AZ Review', 'Refractor', 7.0, true),
  ('explore-scientific-ed80-review', 'Explore Scientific', 'Explore Scientific ED80 Review', 'Refractor', 7.5, true),
  ('gskyer-travel-scope-70-review', 'Gskyer', 'Gskyer Travel Scope 70 Review', 'Refractor', 3.0, true),
  ('meade-etx-125-review', 'Meade', 'Meade ETX 125 Review', 'Maksutov-Cassegrain', 7.4, true),
  ('meade-infinity-70-overview', 'Meade', 'Meade Infinity 70 Review', 'Refractor', 6.5, true),
  ('meade-infinity-80-review', 'Meade', 'Meade Infinity 80 AZ Refractor Overview', 'Refractor', 7.5, true),
  ('meade-infinity-90mm-refractor-overview', 'Meade', 'Meade Infinity 90 AZ Refractor Overview', 'Refractor', 7.5, true),
  ('meade-polaris-130-review', 'Meade', 'Meade Polaris 130 EQ Reflector Review', 'Reflector', 7.0, true),
  ('orion-bl102-review', 'Orion', 'Orion BL102 Review', 'Tabletop Dobsonian', 6.0, true),
  ('orion-bl135-review', 'Orion', 'Orion Bl135 Review', 'Dobsonian', 7.5, true),
  ('orion-skyline-6-review', 'Orion', 'Orion Skyline 6 Review', 'Dobsonian', 9.5, true),
  ('orion-skyline-8-review', 'Orion', 'Orion Skyline 8 Review', 'Dobsonian', 9.5, true),
  ('orion-skyquest-xt10-overview', 'Orion', 'Orion SkyQuest XT10 Overview', 'Dobsonian', 7.8, true),
  ('orion-skyquest-xt4-5-overview', 'Orion', 'Orion SkyQuest XT4.5 Overview', 'Dobsonian', 8.3, true),
  ('orion-skyquest-xt8-dobsonian-review', 'Orion', 'Orion SkyQuest XT8 Classic Dobsonian Telescope Overview', 'Dobsonian', 9.0, true),
  ('radian-75mm-petzval-refractor-telescope-review', 'Radian', 'Radian 75mm Petzval Refractor Telescope Review', 'Astrograph', 8.5, true),
  ('radian-raptor-61-review', 'Radian', 'Radian Raptor 61 Review', 'Refractor', 8.0, true),
  ('redcat-51-review', 'William Optics', 'RedCat 51 Review', 'Astrograph', 9.5, true),
  ('redcat-71-review', 'William Optics', 'RedCat 71 Review', 'Astrograph', 8.5, true),
  ('seestar-s30-review', 'ZWO', 'ZWO Seestar S30 Review', 'Smart Telescope', 9.0, true),
  ('skywatcher-6-traditional-dobsonian-telescope-review', 'SkyWatcher', 'SkyWatcher 6" Dobsonian Telescope Overview', 'Dobsonian', 9.0, true),
  ('skywatcher-8-classic-dobsonian-overview', 'SkyWatcher', 'SkyWatcher 8" Classic Dobsonian Overview', 'Dobsonian', 8.1, true),
  ('skywatcher-esprit-100ed-review', 'SkyWatcher', 'SkyWatcher Esprit 100ED Review', 'Astrograph', 9.5, true),
  ('skywatcher-evostar-ed80-review', 'SkyWatcher', 'Skywatcher EvoStar ED80 Review', 'Refractor', 9.0, true),
  ('skywatcher-flextube-250p-review', 'SkyWatcher', 'SkyWatcher Flextube 250P Review', 'Dobsonian', 8.5, true),
  ('skywatcher-flextube-300p-review', 'SkyWatcher', 'SkyWatcher Flextube 300P Review', 'Dobsonian', 9.0, true),
  ('skywatcher-heritage-130p-overview', 'SkyWatcher', 'SkyWatcher Heritage 130P FlexTube Dobsonian Overview', 'Dobsonian', 8.4, true),
  ('skywatcher-virtuoso-gti-130p-review', 'SkyWatcher', 'SkyWatcher Virtuoso GTI 130P Review', 'Tabletop Dobsonian', 9.5, true),
  ('unistellar-evscope-review', 'UniStellar', 'Unistellar Evscope Review', 'Smart Telescope', 1.0, true),
  ('william-optics-zenithstar-61-review', 'William Optics', 'William Optics ZenithStar 61 Review', 'Refractor', 9.0, true),
  ('william-optics-zenithstar-73-review', 'William Optics', 'William Optics ZenithStar 73 Review', 'Refractor', 9.0, true),
  ('william-optics-zenithstar-81-review', 'William Optics', 'William Optics ZenithStar 81 Review', 'Refractor', 9.0, true),
  ('zhumell-z100-portable-altazimuth-reflector-telescope-review', 'Zhumell', 'Zhumell Z100 Review', 'Tabletop Dobsonian', 8.6, true),
  ('zhumell-z114-portable-altazimuth-reflector-telescope-review', 'Zhumell', 'Zhumell Z114 Review', 'Tabletop Dobsonian', 8.4, true),
  ('zhumell-z12-dobsonian-review', 'Zhumell', 'Zhumell Z12 Dobsonian Review', 'Dobsonian', 9.6, true),
  ('zhumell-z8-deluxe-overview', 'Zhumell', 'Zhumell Z8 Deluxe Dobsonian Overview', 'Dobsonian', 8.6, true)
on conflict (slug) do update set
  brand = excluded.brand,
  model = excluded.model,
  telescope_type = excluded.telescope_type,
  editorial_rating = excluded.editorial_rating,
  is_published = excluded.is_published;
